import PushNotification from 'react-native-push-notification';
import PushNotificationIOS from '@react-native-community/push-notification-ios';
import {PermissionsAndroid, Platform} from 'react-native';

const NotificationManager = {
  requestNotificationPermission: async () => {
    if (Platform.OS === 'ios') {
      const request = await PushNotificationIOS.requestPermissions();
    }

    if (Platform.OS === 'android') {
      try {
        const check = PermissionsAndroid.check(
          PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
        );
        if (!check) {
          const request = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS,
          );
          console.log(request);
        }
      } catch (error) {
        console.log(error);
      }
    }
  },

  createNotificationChannel: () => {
    if (Platform.OS === 'android') {
      try {
        PushNotification.createChannel(
          {
            channelId: 'local-notification-channel', // Unique ID
            channelName: 'Local Notifications',
            channelDescription: 'A channel for local notifications',
            playSound: true,
            soundName: 'default',
            importance: 4,
            vibrate: true,
          },
          created => console.log(`Channel created: ${created}`), // Debug log
        );
      } catch (error) {
        console.log(error);
      }
    }
  },

  sendLocalNotification: () => {
    try {
      if (Platform.OS === 'android') {
        PushNotification.localNotification({
          channelId: 'local-notification-channel', // Must match the created channel ID
          id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
          title: 'My Notification Title', // (optional)
          message: 'My Notification Message', // (required)
          picture: 'https://www.example.tld/picture.jpg', // (optional) Display an picture with the notification, alias of `bigPictureUrl` for Android. default: undefined
          userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
          playSound: false, // (optional) default: true
          soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
          number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
          repeatType: 'day', // (optional) Repeating interval.
          ongoing: true,
        });
      } else if (Platform.OS === 'ios') {
        console.log('Sending local notification for iOS');

        PushNotificationIOS.addNotificationRequest({
          id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
          title: 'My Notification Title', // (optional)
          body: 'My Notification Message', // (required)
          userInfo: {}, // (optional) default: {} (using null throws a JSON value '<null>' error)
          sound: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
        });
      }
    } catch (error) {
      console.log(error);
    }
  },
};

export default NotificationManager;
